import { prisma } from '../utils/prisma.js';

const categories = [
  { name: 'Electronics' },
  { name: 'Books' },
  { name: 'Home & Kitchen' },
  { name: 'Clothing' },
  { name: 'Sports & Outdoors' },
]

const products = [
  // Electronics
  {
    name: 'Wireless Bluetooth Headphones',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life. Features active noise cancellation, premium sound quality, and comfortable over-ear design.',
    price: 79.99,
    listPrice: 99.99,
    brand: 'AudioTech',
    stockQuantity: 50,
    rating: 4.5,
    reviewCount: 3241,
    isPrime: true,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/headphones1/400/400',
      'https://picsum.photos/seed/headphones2/400/400',
      'https://picsum.photos/seed/headphones3/400/400',
    ],
  },
  {
    name: 'Smartphone 128GB',
    description: 'Latest generation smartphone with advanced camera system, 5G connectivity, and all-day battery life. Features a stunning display and powerful processor.',
    price: 599.99,
    listPrice: 699.99,
    brand: 'TechPhone',
    stockQuantity: 30,
    rating: 4.7,
    reviewCount: 8923,
    isPrime: true,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/phone1/400/400',
      'https://picsum.photos/seed/phone2/400/400',
      'https://picsum.photos/seed/phone3/400/400',
    ],
  },
  {
    name: 'Laptop 15.6" 8GB RAM',
    description: 'High-performance laptop perfect for work and entertainment. Features fast processor, ample storage, and crisp display. Ideal for students and professionals.',
    price: 799.99,
    listPrice: 999.99,
    brand: 'LaptopPro',
    stockQuantity: 25,
    rating: 4.6,
    reviewCount: 5678,
    isPrime: true,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/laptop1/400/400',
      'https://picsum.photos/seed/laptop2/400/400',
      'https://picsum.photos/seed/laptop3/400/400',
    ],
  },
  {
    name: 'Smart Watch Fitness Tracker',
    description: 'Advanced fitness tracking smartwatch with heart rate monitor, GPS, and 7-day battery life. Water-resistant and compatible with iOS and Android.',
    price: 199.99,
    listPrice: 249.99,
    brand: 'FitTech',
    stockQuantity: 75,
    rating: 4.4,
    reviewCount: 4567,
    isPrime: true,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/watch1/400/400',
      'https://picsum.photos/seed/watch2/400/400',
    ],
  },
  {
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with precision tracking and long battery life. Perfect for office work and gaming.',
    price: 29.99,
    listPrice: 39.99,
    brand: 'MouseTech',
    stockQuantity: 100,
    rating: 4.3,
    reviewCount: 2345,
    isPrime: false,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/mouse1/400/400',
      'https://picsum.photos/seed/mouse2/400/400',
    ],
  },
  {
    name: 'USB-C Charging Cable',
    description: 'Fast charging USB-C cable, 6 feet long. Compatible with all USB-C devices. Durable and reliable.',
    price: 12.99,
    listPrice: 19.99,
    brand: 'CablePro',
    stockQuantity: 200,
    rating: 4.2,
    reviewCount: 1234,
    isPrime: true,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/cable1/400/400',
    ],
  },
  {
    name: '4K Ultra HD TV 55"',
    description: 'Stunning 4K Ultra HD Smart TV with HDR support. Features voice control, streaming apps, and crystal-clear picture quality.',
    price: 499.99,
    listPrice: 699.99,
    brand: 'TVMax',
    stockQuantity: 15,
    rating: 4.8,
    reviewCount: 3456,
    isPrime: true,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/tv1/400/400',
      'https://picsum.photos/seed/tv2/400/400',
      'https://picsum.photos/seed/tv3/400/400',
    ],
  },
  {
    name: 'Gaming Keyboard RGB',
    description: 'Mechanical gaming keyboard with RGB backlighting. Features customizable keys and responsive switches for the ultimate gaming experience.',
    price: 89.99,
    listPrice: 119.99,
    brand: 'GameTech',
    stockQuantity: 60,
    rating: 4.5,
    reviewCount: 2789,
    isPrime: true,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/keyboard1/400/400',
      'https://picsum.photos/seed/keyboard2/400/400',
    ],
  },
  {
    name: 'Portable Bluetooth Speaker',
    description: 'Waterproof portable speaker with 360-degree sound. 20-hour battery life and built-in microphone for hands-free calls.',
    price: 49.99,
    listPrice: 69.99,
    brand: 'SoundWave',
    stockQuantity: 80,
    rating: 4.4,
    reviewCount: 3456,
    isPrime: true,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/speaker1/400/400',
      'https://picsum.photos/seed/speaker2/400/400',
    ],
  },
  {
    name: 'Tablet 10.1" 64GB',
    description: 'Versatile tablet perfect for reading, browsing, and entertainment. Features high-resolution display and long battery life.',
    price: 249.99,
    listPrice: 299.99,
    brand: 'TabletPro',
    stockQuantity: 40,
    rating: 4.3,
    reviewCount: 1890,
    isPrime: true,
    categoryName: 'Electronics',
    images: [
      'https://picsum.photos/seed/tablet1/400/400',
      'https://picsum.photos/seed/tablet2/400/400',
    ],
  },
  // Books
  {
    name: 'The Great Novel - Hardcover',
    description: 'A captivating story of adventure and discovery. This bestseller has captured the hearts of millions of readers worldwide.',
    price: 24.99,
    listPrice: 29.99,
    brand: 'BookHouse',
    stockQuantity: 100,
    rating: 4.6,
    reviewCount: 5678,
    isPrime: true,
    categoryName: 'Books',
    images: [
      'https://picsum.photos/seed/book1/400/400',
      'https://picsum.photos/seed/book2/400/400',
    ],
  },
  {
    name: 'Programming Fundamentals',
    description: 'Comprehensive guide to programming concepts and best practices. Perfect for beginners and intermediate developers.',
    price: 39.99,
    listPrice: 49.99,
    brand: 'TechBooks',
    stockQuantity: 75,
    rating: 4.5,
    reviewCount: 2345,
    isPrime: true,
    categoryName: 'Books',
    images: [
      'https://picsum.photos/seed/book3/400/400',
    ],
  },
  {
    name: 'Mystery Thriller Collection',
    description: 'Three gripping mystery novels in one collection. Perfect for fans of suspense and intrigue.',
    price: 19.99,
    listPrice: 34.99,
    brand: 'MysteryPress',
    stockQuantity: 50,
    rating: 4.4,
    reviewCount: 1234,
    isPrime: false,
    categoryName: 'Books',
    images: [
      'https://picsum.photos/seed/book4/400/400',
    ],
  },
  {
    name: 'Cookbook: Healthy Recipes',
    description: 'Over 200 healthy and delicious recipes for everyday cooking. Features nutritional information and cooking tips.',
    price: 27.99,
    listPrice: 35.99,
    brand: 'CookHouse',
    stockQuantity: 90,
    rating: 4.7,
    reviewCount: 3456,
    isPrime: true,
    categoryName: 'Books',
    images: [
      'https://picsum.photos/seed/book5/400/400',
    ],
  },
  {
    name: 'Science Fiction Classic',
    description: 'A timeless science fiction masterpiece that explores the future of humanity and technology.',
    price: 16.99,
    listPrice: 22.99,
    brand: 'SciFiBooks',
    stockQuantity: 120,
    rating: 4.8,
    reviewCount: 7890,
    isPrime: true,
    categoryName: 'Books',
    images: [
      'https://picsum.photos/seed/book6/400/400',
    ],
  },
  {
    name: 'Business Strategy Guide',
    description: 'Essential strategies for building and growing a successful business. Written by industry experts.',
    price: 34.99,
    listPrice: 44.99,
    brand: 'BusinessBooks',
    stockQuantity: 60,
    rating: 4.5,
    reviewCount: 1890,
    isPrime: true,
    categoryName: 'Books',
    images: [
      'https://picsum.photos/seed/book7/400/400',
    ],
  },
  // Home & Kitchen
  {
    name: 'Stainless Steel Cookware Set',
    description: '10-piece cookware set with non-stick coating. Includes pots, pans, and lids. Dishwasher safe and oven safe up to 400°F.',
    price: 89.99,
    listPrice: 129.99,
    brand: 'KitchenPro',
    stockQuantity: 45,
    rating: 4.6,
    reviewCount: 4567,
    isPrime: true,
    categoryName: 'Home & Kitchen',
    images: [
      'https://picsum.photos/seed/cookware1/400/400',
      'https://picsum.photos/seed/cookware2/400/400',
      'https://picsum.photos/seed/cookware3/400/400',
    ],
  },
  {
    name: 'Coffee Maker Programmable',
    description: '12-cup programmable coffee maker with auto-shutoff and brew strength control. Perfect for coffee lovers.',
    price: 49.99,
    listPrice: 69.99,
    brand: 'BrewMaster',
    stockQuantity: 70,
    rating: 4.5,
    reviewCount: 3456,
    isPrime: true,
    categoryName: 'Home & Kitchen',
    images: [
      'https://picsum.photos/seed/coffee1/400/400',
      'https://picsum.photos/seed/coffee2/400/400',
    ],
  },
  {
    name: 'Air Fryer 5.8 Quart',
    description: 'Large capacity air fryer with digital display and preset cooking functions. Healthier cooking with less oil.',
    price: 79.99,
    listPrice: 99.99,
    brand: 'FryTech',
    stockQuantity: 55,
    rating: 4.7,
    reviewCount: 5678,
    isPrime: true,
    categoryName: 'Home & Kitchen',
    images: [
      'https://picsum.photos/seed/airfryer1/400/400',
      'https://picsum.photos/seed/airfryer2/400/400',
    ],
  },
  {
    name: 'Stand Mixer 5 Quart',
    description: 'Powerful stand mixer with multiple attachments. Perfect for baking and cooking. Includes dough hook, whisk, and paddle.',
    price: 199.99,
    listPrice: 249.99,
    brand: 'MixMaster',
    stockQuantity: 30,
    rating: 4.8,
    reviewCount: 2345,
    isPrime: true,
    categoryName: 'Home & Kitchen',
    images: [
      'https://picsum.photos/seed/mixer1/400/400',
      'https://picsum.photos/seed/mixer2/400/400',
    ],
  },
  {
    name: 'Bedding Set Queen Size',
    description: 'Luxurious 6-piece bedding set including comforter, sheets, and pillowcases. Soft and breathable cotton blend.',
    price: 59.99,
    listPrice: 89.99,
    brand: 'ComfortHome',
    stockQuantity: 85,
    rating: 4.4,
    reviewCount: 1890,
    isPrime: true,
    categoryName: 'Home & Kitchen',
    images: [
      'https://picsum.photos/seed/bedding1/400/400',
      'https://picsum.photos/seed/bedding2/400/400',
    ],
  },
  {
    name: 'Robot Vacuum Cleaner',
    description: 'Smart robot vacuum with app control and scheduling. Automatically returns to charging dock. Perfect for pet hair.',
    price: 249.99,
    listPrice: 349.99,
    brand: 'CleanBot',
    stockQuantity: 40,
    rating: 4.6,
    reviewCount: 4567,
    isPrime: true,
    categoryName: 'Home & Kitchen',
    images: [
      'https://picsum.photos/seed/vacuum1/400/400',
      'https://picsum.photos/seed/vacuum2/400/400',
    ],
  },
  {
    name: 'Dining Table Set 6-Piece',
    description: 'Modern dining table with 4 chairs. Solid wood construction with elegant finish. Seats 4-6 people comfortably.',
    price: 399.99,
    listPrice: 549.99,
    brand: 'FurniturePlus',
    stockQuantity: 20,
    rating: 4.5,
    reviewCount: 1234,
    isPrime: false,
    categoryName: 'Home & Kitchen',
    images: [
      'https://picsum.photos/seed/table1/400/400',
      'https://picsum.photos/seed/table2/400/400',
    ],
  },
  {
    name: 'Smart Thermostat',
    description: 'Wi-Fi enabled smart thermostat with app control. Learns your schedule and saves energy. Compatible with Alexa and Google Home.',
    price: 129.99,
    listPrice: 179.99,
    brand: 'SmartHome',
    stockQuantity: 65,
    rating: 4.7,
    reviewCount: 3456,
    isPrime: true,
    categoryName: 'Home & Kitchen',
    images: [
      'https://picsum.photos/seed/thermostat1/400/400',
    ],
  },
  // Clothing
  {
    name: 'Cotton T-Shirt Pack (3-Pack)',
    description: 'Soft cotton t-shirts in assorted colors. Comfortable fit and durable fabric. Machine washable.',
    price: 24.99,
    listPrice: 39.99,
    brand: 'ClothCo',
    stockQuantity: 150,
    rating: 4.3,
    reviewCount: 5678,
    isPrime: true,
    categoryName: 'Clothing',
    images: [
      'https://picsum.photos/seed/tshirt1/400/400',
      'https://picsum.photos/seed/tshirt2/400/400',
    ],
  },
  {
    name: 'Denim Jeans Classic Fit',
    description: 'Classic fit denim jeans with stretch comfort. Available in multiple sizes. Durable and stylish.',
    price: 39.99,
    listPrice: 59.99,
    brand: 'DenimPro',
    stockQuantity: 100,
    rating: 4.4,
    reviewCount: 3456,
    isPrime: true,
    categoryName: 'Clothing',
    images: [
      'https://picsum.photos/seed/jeans1/400/400',
      'https://picsum.photos/seed/jeans2/400/400',
    ],
  },
  {
    name: 'Running Shoes Athletic',
    description: 'Lightweight running shoes with cushioned sole and breathable mesh upper. Perfect for running and workouts.',
    price: 69.99,
    listPrice: 99.99,
    brand: 'RunFast',
    stockQuantity: 80,
    rating: 4.6,
    reviewCount: 4567,
    isPrime: true,
    categoryName: 'Clothing',
    images: [
      'https://picsum.photos/seed/shoes1/400/400',
      'https://picsum.photos/seed/shoes2/400/400',
    ],
  },
  {
    name: 'Winter Jacket Waterproof',
    description: 'Warm and waterproof winter jacket with insulated lining. Perfect for cold weather and outdoor activities.',
    price: 89.99,
    listPrice: 129.99,
    brand: 'OutdoorGear',
    stockQuantity: 60,
    rating: 4.5,
    reviewCount: 2345,
    isPrime: true,
    categoryName: 'Clothing',
    images: [
      'https://picsum.photos/seed/jacket1/400/400',
      'https://picsum.photos/seed/jacket2/400/400',
    ],
  },
  {
    name: 'Dress Shirt Business',
    description: 'Professional dress shirt in classic colors. Wrinkle-resistant fabric. Perfect for office and formal occasions.',
    price: 34.99,
    listPrice: 49.99,
    brand: 'FormalWear',
    stockQuantity: 90,
    rating: 4.4,
    reviewCount: 1890,
    isPrime: true,
    categoryName: 'Clothing',
    images: [
      'https://picsum.photos/seed/shirt1/400/400',
    ],
  },
  {
    name: 'Yoga Pants Activewear',
    description: 'Comfortable yoga pants with moisture-wicking fabric. Perfect for yoga, gym, or casual wear.',
    price: 29.99,
    listPrice: 44.99,
    brand: 'ActiveFit',
    stockQuantity: 110,
    rating: 4.5,
    reviewCount: 3456,
    isPrime: true,
    categoryName: 'Clothing',
    images: [
      'https://picsum.photos/seed/pants1/400/400',
      'https://picsum.photos/seed/pants2/400/400',
    ],
  },
  {
    name: 'Sneakers Casual',
    description: 'Stylish casual sneakers with comfortable cushioning. Perfect for everyday wear. Available in multiple colors.',
    price: 54.99,
    listPrice: 79.99,
    brand: 'ShoeStyle',
    stockQuantity: 95,
    rating: 4.3,
    reviewCount: 2789,
    isPrime: true,
    categoryName: 'Clothing',
    images: [
      'https://picsum.photos/seed/sneakers1/400/400',
      'https://picsum.photos/seed/sneakers2/400/400',
    ],
  },
  {
    name: 'Hoodie Sweatshirt',
    description: 'Cozy hoodie with front pocket and drawstring hood. Soft fleece lining. Perfect for casual wear.',
    price: 39.99,
    listPrice: 59.99,
    brand: 'ComfortWear',
    stockQuantity: 120,
    rating: 4.4,
    reviewCount: 1234,
    isPrime: true,
    categoryName: 'Clothing',
    images: [
      'https://picsum.photos/seed/hoodie1/400/400',
    ],
  },
  // Sports & Outdoors
  {
    name: 'Yoga Mat Premium',
    description: 'Non-slip yoga mat with extra cushioning. Eco-friendly material. Perfect for yoga, pilates, and exercise.',
    price: 24.99,
    listPrice: 34.99,
    brand: 'YogaLife',
    stockQuantity: 130,
    rating: 4.5,
    reviewCount: 4567,
    isPrime: true,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/yogamat1/400/400',
    ],
  },
  {
    name: 'Dumbbell Set Adjustable',
    description: 'Adjustable dumbbell set with weight range from 5-50 lbs. Perfect for home workouts and strength training.',
    price: 149.99,
    listPrice: 199.99,
    brand: 'FitGear',
    stockQuantity: 50,
    rating: 4.6,
    reviewCount: 2345,
    isPrime: true,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/dumbbell1/400/400',
      'https://picsum.photos/seed/dumbbell2/400/400',
    ],
  },
  {
    name: 'Camping Tent 4-Person',
    description: 'Spacious 4-person camping tent with waterproof coating. Easy setup and includes rainfly. Perfect for family camping.',
    price: 89.99,
    listPrice: 129.99,
    brand: 'OutdoorPro',
    stockQuantity: 35,
    rating: 4.4,
    reviewCount: 1890,
    isPrime: true,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/tent1/400/400',
      'https://picsum.photos/seed/tent2/400/400',
    ],
  },
  {
    name: 'Bicycle Mountain Bike',
    description: '21-speed mountain bike with front suspension and disc brakes. Perfect for trails and off-road riding.',
    price: 299.99,
    listPrice: 399.99,
    brand: 'BikePro',
    stockQuantity: 25,
    rating: 4.7,
    reviewCount: 3456,
    isPrime: false,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/bike1/400/400',
      'https://picsum.photos/seed/bike2/400/400',
    ],
  },
  {
    name: 'Tennis Racket Professional',
    description: 'Professional tennis racket with carbon fiber frame. Perfect balance and control. Includes racket cover.',
    price: 79.99,
    listPrice: 119.99,
    brand: 'TennisPro',
    stockQuantity: 70,
    rating: 4.5,
    reviewCount: 1234,
    isPrime: true,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/racket1/400/400',
    ],
  },
  {
    name: 'Hiking Backpack 40L',
    description: 'Durable hiking backpack with multiple compartments and hydration system compatibility. Comfortable padded straps.',
    price: 59.99,
    listPrice: 89.99,
    brand: 'HikeGear',
    stockQuantity: 85,
    rating: 4.6,
    reviewCount: 2789,
    isPrime: true,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/backpack1/400/400',
      'https://picsum.photos/seed/backpack2/400/400',
    ],
  },
  {
    name: 'Basketball Official Size',
    description: 'Official size basketball with premium composite leather. Perfect for indoor and outdoor play.',
    price: 24.99,
    listPrice: 34.99,
    brand: 'BallPro',
    stockQuantity: 140,
    rating: 4.4,
    reviewCount: 5678,
    isPrime: true,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/basketball1/400/400',
    ],
  },
  {
    name: 'Fishing Rod Combo',
    description: 'Complete fishing rod and reel combo. Includes fishing line and tackle box. Perfect for beginners and experienced anglers.',
    price: 49.99,
    listPrice: 69.99,
    brand: 'FishGear',
    stockQuantity: 60,
    rating: 4.3,
    reviewCount: 1890,
    isPrime: true,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/fishing1/400/400',
      'https://picsum.photos/seed/fishing2/400/400',
    ],
  },
  {
    name: 'Resistance Bands Set',
    description: '5-piece resistance bands set with different resistance levels. Includes door anchor and exercise guide.',
    price: 19.99,
    listPrice: 29.99,
    brand: 'FitBand',
    stockQuantity: 160,
    rating: 4.5,
    reviewCount: 3456,
    isPrime: true,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/bands1/400/400',
    ],
  },
  {
    name: 'Golf Club Set',
    description: 'Complete golf club set with driver, irons, putter, and bag. Perfect for beginners and intermediate players.',
    price: 199.99,
    listPrice: 299.99,
    brand: 'GolfPro',
    stockQuantity: 30,
    rating: 4.4,
    reviewCount: 1234,
    isPrime: false,
    categoryName: 'Sports & Outdoors',
    images: [
      'https://picsum.photos/seed/golf1/400/400',
      'https://picsum.photos/seed/golf2/400/400',
    ],
  },
]

async function main() {
  console.log('Starting seed...')

  // Create categories
  const categoryMap = {}
  for (const cat of categories) {
    let category = await prisma.category.findFirst({
      where: { name: cat.name },
    })
    
    if (!category) {
      category = await prisma.category.create({
        data: cat,
      })
      console.log(`Created category: ${cat.name}`)
    } else {
      console.log(`Category already exists: ${cat.name}`)
    }
    
    categoryMap[cat.name] = category.id
  }

  // Create products
  for (const product of products) {
    const categoryId = categoryMap[product.categoryName]
    
    const createdProduct = await prisma.product.create({
      data: {
        name: product.name,
        description: product.description,
        price: product.price,
        listPrice: product.listPrice,
        brand: product.brand,
        stockQuantity: product.stockQuantity,
        rating: product.rating,
        reviewCount: product.reviewCount,
        isPrime: product.isPrime,
        categoryId: categoryId,
        images: {
          create: product.images.map((url, index) => ({
            imageUrl: url,
            isPrimary: index === 0,
            displayOrder: index,
          })),
        },
      },
    })
    console.log(`Created product: ${product.name}`)
  }

  console.log('Seed completed!')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
